# Generated by Django 3.0.3 on 2020-04-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_user_talked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.TextField()),
                ('time', models.DateTimeField(null=True)),
                ('commit_number', models.IntegerField(default=0, null=True)),
                ('talker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talker_user', to='User.User')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.TextField()),
                ('time', models.DateTimeField(null=True)),
                ('commiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commiter_user', to='User.User')),
                ('talk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Talk.Talk')),
            ],
        ),
    ]
