# Generated by Django 3.0.3 on 2020-04-29 16:08

import SmartDjango.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', SmartDjango.models.fields.CharField(blank=True, default=None, max_length=32, null=True, unique=True)),
                ('password', SmartDjango.models.fields.CharField(max_length=32)),
                ('salt', SmartDjango.models.fields.CharField(default=None, max_length=10)),
                ('pwd_change_time', SmartDjango.models.fields.FloatField(blank=True, default=0, null=True)),
                ('invite_code', SmartDjango.models.fields.CharField(blank=True, default=None, max_length=255, null=True)),
                ('inviter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
    ]
