# Generated by Django 3.0.3 on 2020-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='talked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
